
# Settings relevant for the hitobito_aolv wagon
# Overrides settings from the main application
application:
  logo:
    image: logo_aolv.png
    height: 50
    width: 173

  footer:
    links:
      "Dokumentation": https://github.com/MartinGantenbein/hitobito_aolv/blob/master/README.md
      "Kontakt": 'mailto:webmaster@aolv.ch'

mailchimp:
  enabled: false
