
# Settings relevant for the hitobito_aolv wagon
# Overrides settings from the main application
application:
  logo:
    image: logo_aolv.png
    height: 50
    width: 173
  footer:
    links: {https://www.aolv.ch}

mailchimp:
  enabled: false